apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-web-app
  annotations:
    github.com/project-slug: ChunPingWang/python-web-app
spec:
  type: other
  lifecycle: unknown
  owner: ChunPingWang
